In [ ]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

x = np.array([0.5, 0.1, -0.2])

target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass

# Calculate output error
error = target - output                      # <-- LINE 1

### Notebook grading
error_answer = target - output

if error == error_answer:
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

# Calculate error term for output layer

# output * (1 - output) is the derivative of the sigmoid activation
# σ'(z) = σ(z)(1 - σ(z)).
# In back-propagation you multiply that derivative by the error coming from
# the loss:

# error             = (y_true - output)           # ∂L/∂output
# output_error_term = error * output * (1 - output) # ∂L/∂z

# So output_error_term is not the derivative of the sigmoid by itself; it is the
# gradient of the loss with respect to the neuron's pre-activation input z.
# In other words, it's the product of:

# 1. the derivative of the loss w.r.t. the neuron's output (error), and
# 2. the derivative of the sigmoid w.r.t. its input (output * (1-output)).
# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output) # <-- LINE 2

### Notebook grading

del_err_output_answer = error_answer * output * (1 - output)

if output_error_term == del_err_output_answer:
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")


# Calculate error term for hidden layer
# hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
#                     hidden_layer_output * (1 - hidden_layer_output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output) # <-- LINE 3

### Notebook grading

del_err_hidden_answer = np.dot(del_err_output_answer, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

test_h = del_err_hidden_answer == hidden_error_term

if test_h.all():
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

# Calculate change in weights for hidden layer to output layer
# delta_w_h_o = learnrate  *output_error_term*  hidden_layer_output
# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output # <-- LINE 4

### Notebook grading
delta_w_h_o_answer = learnrate * del_err_output_answer * hidden_layer_output

test_w_h_o = delta_w_h_o_answer == delta_w_h_o

if test_w_h_o.all():
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

# Calculate change in weights for input layer to hidden layer
# delta_w_i_h = learnrate  *hidden_error_term*  x[:, None]

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None] # <-- LINE 5
print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

### Notebook grading

delta_w_i_h_answer = learnrate * del_err_hidden_answer * x[:, None]


test_w_i_h = delta_w_i_h_answer == delta_w_i_h

if test_w_i_h.all():
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")
    
print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)



Well done!
Well done!
Well done!
Well done!
Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]
Well done!
Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]


In [21]:
# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)

### Notebook grading

del_err_output_answer = error_answer * output * (1 - output)

if output_error_term == del_err_output_answer:
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

Well done!


In [22]:
# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

### Notebook grading

del_err_hidden_answer = np.dot(del_err_output_answer, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

test_h = del_err_hidden_answer == hidden_error_term

if test_h.all():
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

Well done!


In [23]:
# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

### Notebook grading
delta_w_h_o_answer = learnrate * del_err_output_answer * hidden_layer_output

test_w_h_o = delta_w_h_o_answer == delta_w_h_o

if test_w_h_o.all():
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

Well done!


In [24]:
# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]
print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

### Notebook grading

delta_w_i_h_answer = learnrate * del_err_hidden_answer * x[:, None]


test_w_i_h = delta_w_i_h_answer == delta_w_i_h

if test_w_i_h.all():
    print("Well done!")
else:
    print("Try again. Something is wrong in your submission")

Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]
Well done!
