In [2]:
import torch

In [5]:
## torch.rand()

In [6]:
torch.rand(5)

tensor([0.0172, 0.3152, 0.1039, 0.0559, 0.4318])

In [7]:
torch.rand(5, 5)

tensor([[0.3005, 0.5307, 0.0506, 0.7799, 0.5718],
        [0.5960, 0.6300, 0.8936, 0.3779, 0.6295],
        [0.6082, 0.5375, 0.3223, 0.7011, 0.4415],
        [0.2314, 0.7563, 0.2230, 0.2633, 0.0657],
        [0.3942, 0.3352, 0.2214, 0.2713, 0.4043]])

In [8]:
## torch.ones

In [9]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [10]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
## torch.arange

In [3]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
## torch.tril

In [5]:
"""
Creates a 5x5 lower triangular matrix with random values.

This operation is a composition of two PyTorch functions:

1. `torch.rand(5, 5)`:
   - Creates a 2D tensor (a matrix) of size 5x5.
   - Fills the tensor with random numbers sampled from a uniform
     distribution on the interval [0, 1).

2. `torch.tril(...)`:
   - Takes the randomly generated 5x5 tensor as input.
   - Returns a new tensor where all elements in the upper triangle
     (above the main diagonal) are set to zero.
   - The elements on the main diagonal and in the lower triangle
     are kept from the original random tensor.

The result is a lower triangular matrix, a common structure used for
creating causal masks in transformer models.
"""
result = torch.tril(torch.rand(5, 5))

print(result)

tensor([[0.8475, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1402, 0.3179, 0.0000, 0.0000, 0.0000],
        [0.4979, 0.0432, 0.3203, 0.0000, 0.0000],
        [0.3994, 0.2619, 0.8413, 0.2218, 0.0000],
        [0.9573, 0.2471, 0.5639, 0.9865, 0.9913]])


In [15]:
## torch.cat

In [6]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [10]:
# Concatenate along rows
print(tensor_a)
print(tensor_b)

print("\n")

res = torch.cat((tensor_a, tensor_b), dim=0)
print(res)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [11]:
# Concatenate along columns
torch.cat((tensor_a, tensor_b), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [19]:
## tensor.view()

In [13]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
x_reshaped = x.view(3, 4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
x_reshaped.view(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])